id: I5B22ADB4
ocr_import_info:
  timestamp: '2023-09-29T16:05:27.404019+00:00'
  batch_id: batch-bb5c
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Dharma Kyab
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-09-29 16:30:07.862458+00:00
last_modified: 2023-09-29 16:30:07.862466+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN3032
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3CN3032
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྟ་ནག་རྣམ་འགྲེལ། ༼སྟོད་ཆ་དང་སྨད་ཆ།༽
  languages:
  - bo
  author: རྟ་ནག་པ་དགེ་འདུན་བློ་བཟང་།
statistics:
  ocr_word_mean_confidence_index: 0.994310732920754
  ocr_word_median_confidence_index: 1.0
bases:
  I3CN3503:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN3503
      total_pages: 442
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN3503.txt
    statistics:
      ocr_word_median_confidence_index: 1.0
      ocr_word_mean_confidence_index: 0.9919185362206295
  I3CN3504:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN3504
      total_pages: 687
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I3CN3504.txt
    statistics:
      ocr_word_median_confidence_index: 1.0
      ocr_word_mean_confidence_index: 0.9958334569734472
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
